add test for velocity verlet
AmpersandTV/aesara-hmc pull request #2
Opened 2021-05-12 10:50 UTC by rlouf

This PR add tests for the velocity verlet algorithm implementation

2021-05-12 10:52 UTC, rlouf commented on tests/test_integrators.py
> +    )
This fails with the following error message:

```
ValueError: Scan cannot parse the return value of your lambda expression, which is: (Elemwise{add,no_inplace}.0, Elemwise{sub,no_inplace}.0, Sum{acc_dtype=float64}.0, [Elemwise{mul}.0])
```

and I cannot figure out why after reading the documentation and the code.

2021-05-12 20:10 UTC, brandonwillard requested changes
This change breaks `mypy` checking.  Did you set up `pre-commit`, because it should've prevented this commit?

2021-05-12 20:42 UTC, brandonwillard commented
@rlouf, I've added a commit that adjust the use of `aesara.function` and `aesara.scan` so that the evaluations can be performed.

2021-05-14 14:49 UTC, rlouf commented
@brandonwillard I fixed the few bugs that were left, added tests to check that we integrate the correct trajectory, and a test on 2D state vectors. Good on my end.

2021-05-14 18:58 UTC, merged